module.exports.config = {
    name: "upt",
    version: "1.0.5",
    hasPermssion: 0,
    credits: "Tpk",
    description: "sailenh",
    commandCategory: "Tiện ích",
    usages: "Tiện ích",
    cooldowns: 0
};

module.exports.run = async ({ api, event }) => {
  const allicon = ["💞","💖","💗","💜","🌸","💗","💝","🎀","🌹","🍁","🎊","🌟","🍁"];
const icon = allicon[Math.floor(Math.random()*allicon.length)];
const axios = require('axios');
    const request = require('request');
    const fs = require("fs");
    var os = require("os");
    var cpus = os.cpus();
    var chips;
    for (var i of cpus) chips = i.model, speed = i.speed;
    if (cpus == undefined);
  const timeStart = Date.now();
  /*const res = await axios.get(`https://tan.kizz-kinncuti.repl.co/images/cosplay`);
var tpk = res.data.url;*/
  const moment = require("moment-timezone");
  const timeNow = moment.tz("Asia/Ho_Chi_Minh").format("DD/MM/YYYY || HH:mm:ss");
  const time = process.uptime(),
hours = Math.floor(time / (60 * 60)),
minutes = Math.floor((time % (60 * 60)) / 60),
seconds = Math.floor(time % 60);
  const dateNow = Date.now();
  const xuly = Math.floor((Date.now() - global.client.timeStart)/4444)
 var trinhtrang = xuly < 10 ? "Tốt ✔️":
  xuly > 10 && xuly < 100 ? "Ổn định 📊" : "deplay ";
var tpk = ["https://i.imgur.com/YT4fiIv.mp4",
  "https://i.imgur.com/ieNbUuN.mp4",
  "https://i.imgur.com/sW9I9WX.mp4",
  "https://i.imgur.com/1aXmTrO.mp4",
  "https://i.imgur.com/vpvhZtQ.mp4",
  "https://i.imgur.com/dzT43pY.mp4",
  "https://i.imgur.com/bGbFGzr.mp4",
  "https://i.imgur.com/Io30eVo.mp4",
  "https://i.imgur.com/XCC2HCy.mp4",
  "https://i.imgur.com/LlRje2D.mp4",
  "https://i.imgur.com/YV2Wzoq.mp4",
  "https://i.imgur.com/y2c4SJf.mp4",
  "https://i.imgur.com/mWd1ZxA.mp4",
  "https://i.imgur.com/nTSrod9.mp4",
  "https://i.imgur.com/Vy4Esss.mp4",
  "https://i.imgur.com/GXo6zmf.mp4",
  "https://i.imgur.com/8OhiCiW.mp4",
  "https://i.imgur.com/Dnou58v.mp4",
  "https://i.imgur.com/dcBSemx.mp4",
  "https://i.imgur.com/xJUrqOK.mp4",
  "https://i.imgur.com/LtP2aCo.mp4",
  "https://i.imgur.com/CoHsfGq.mp4",
  "https://i.imgur.com/BNfXX5q.mp4",
  "https://i.imgur.com/qYQPkvP.mp4",
  "https://i.imgur.com/6NgvPF3.mp4",
  "https://i.imgur.com/ca2yBhv.mp4",
  "https://i.imgur.com/H8Bau50.mp4",
  "https://i.imgur.com/SdUsR7W.mp4",
  "https://i.imgur.com/wSmgclj.mp4",
  "https://i.imgur.com/L5uNi3l.mp4",
  "https://i.imgur.com/9nbup0Y.mp4",
  "https://i.imgur.com/cBQvhYJ.mp4",
  "https://i.imgur.com/9y5N7Ef.mp4",
  "https://i.imgur.com/PtpRVOa.mp4",
  "https://i.imgur.com/tTfCC3n.mp4",
  "https://i.imgur.com/aRrtkHd.mp4",
  "https://i.imgur.com/Q2pWzAi.mp4",
  "https://i.imgur.com/1NCnpfS.mp4",
  "https://i.imgur.com/z8nn0r3.mp4",
  "https://i.imgur.com/tf59GxV.mp4",
  "https://i.imgur.com/AxoNEhW.mp4",
  "https://i.imgur.com/Ia9Yx2U.mp4",
  "https://i.imgur.com/sbRLn2k.mp4",
  "https://i.imgur.com/msrG9Hg.mp4",
  "https://i.imgur.com/vkNBKnb.mp4",
  "https://i.imgur.com/Cp4wbP9.mp4",
  "https://i.imgur.com/P2GbX7o.mp4",
  "https://i.imgur.com/4bR7QR0.mp4",
  "https://i.imgur.com/cDLGu7K.mp4",
  "https://i.imgur.com/409GY0m.mp4",
  "https://i.imgur.com/6vwvqIn.mp4",
  "https://i.imgur.com/cZYdGaY.mp4",
  "https://i.imgur.com/jRL4bMo.mp4",
  "https://i.imgur.com/Pv3ukt8.mp4",
  "https://i.imgur.com/V48iXIg.mp4",
  "https://i.imgur.com/hd73w9F.mp4",
  "https://i.imgur.com/4E2TwSI.mp4",
  "https://i.imgur.com/rE8LNgI.mp4",
  "https://i.imgur.com/Nmi43Xq.mp4",
  "https://i.imgur.com/62D82Ac.mp4",
  "https://i.imgur.com/qizOjrb.mp4",
  "https://i.imgur.com/JeQzFk6.mp4",
  "https://i.imgur.com/GO038XI.mp4",
  "https://i.imgur.com/tWypNCc.mp4",
  "https://i.imgur.com/1wuNUeu.mp4",
  "https://i.imgur.com/yzYnvIn.mp4",
  "https://i.imgur.com/uaCOgF2.mp4",
  "https://i.imgur.com/CIOKrko.mp4",
  "https://i.imgur.com/8Phezwv.mp4",
  "https://i.imgur.com/wf5bMoT.mp4",
  "https://i.imgur.com/BFwI2z3.mp4",
  "https://i.imgur.com/hnpydp3.mp4",
  "https://i.imgur.com/XZyfCc4.mp4",
  "https://i.imgur.com/IoObe5h.mp4",
  "https://i.imgur.com/IZkVoBQ.mp4",
  "https://i.imgur.com/lUK6nz7.mp4",
  "https://i.imgur.com/X6NX5bn.mp4",
  "https://i.imgur.com/feShXAm.mp4",
  "https://i.imgur.com/HrUx4rv.mp4",
  "https://i.imgur.com/4yO0W3J.mp4",
  "https://i.imgur.com/PQpcEtL.mp4",
  "https://i.imgur.com/ZTBPlUu.mp4",
  "https://i.imgur.com/2TRymKO.mp4",
  "https://i.imgur.com/E4OSY5u.mp4",
  "https://i.imgur.com/jMSfRbM.mp4",
  "https://i.imgur.com/BQRr0JA.mp4",
  "https://i.imgur.com/QpNRmrC.mp4",
  "https://i.imgur.com/jVsOqRG.mp4",
  "https://i.imgur.com/47YUWRy.mp4",
  "https://i.imgur.com/h2ULlnC.mp4",
  "https://i.imgur.com/EgP0DrC.mp4",
  "https://i.imgur.com/VrOmvb6.mp4",
  "https://i.imgur.com/tX8KdKG.mp4",
  "https://i.imgur.com/hfvxF5E.mp4",
  "https://i.imgur.com/VP8pcLd.mp4",
  "https://i.imgur.com/XoBIMtU.mp4",
  "https://i.imgur.com/XFVFhUV.mp4",
  "https://i.imgur.com/RGjNicg.mp4",
  "https://i.imgur.com/HheyOwt.mp4",
  "https://i.imgur.com/M1Fj3wu.mp4",
  "https://i.imgur.com/qfNfkz2.mp4",
  "https://i.imgur.com/tospiaC.mp4",
  "https://i.imgur.com/m81CW4U.mp4",
  "https://i.imgur.com/gurdGjT.mp4",
  "https://i.imgur.com/ibmipX9.mp4",
  "https://i.imgur.com/502CZcD.mp4",
  "https://i.imgur.com/x16OSJy.mp4",
  "https://i.imgur.com/ytzFm0V.mp4",
  "https://i.imgur.com/5E6EVdH.mp4",
  "https://i.imgur.com/qBZWnqu.mp4",
  "https://i.imgur.com/bzVhchr.mp4",
  "https://i.imgur.com/PcCtfOR.mp4",
  "https://i.imgur.com/Gi1pCc3.mp4",
  "https://i.imgur.com/OJHBEoB.mp4",
  "https://i.imgur.com/xHpTbFv.mp4",
  "https://i.imgur.com/mVZdnVy.mp4",
  "https://i.imgur.com/mYuPmMC.mp4",
  "https://i.imgur.com/7HbwBld.mp4",
  "https://i.imgur.com/UrMJMMd.mp4",
  "https://i.imgur.com/64g5UON.mp4",
  "https://i.imgur.com/B2ES0w9.mp4",
  "https://i.imgur.com/k6MEzay.mp4",
  "https://i.imgur.com/tQmNEL1.mp4",
  "https://i.imgur.com/g4aiqXF.mp4",
  "https://i.imgur.com/31WUOyh.mp4",
  "https://i.imgur.com/cIw2oIM.mp4",
  "https://i.imgur.com/MJ55yVI.mp4",
  "https://i.imgur.com/Bkoi05h.mp4",
  "https://i.imgur.com/L0DxQW0.mp4",
  "https://i.imgur.com/V2wrqAf.mp4",
  "https://i.imgur.com/1YpsHiV.mp4",
  "https://i.imgur.com/eHPviz7.mp4",
  "https://i.imgur.com/DtvEceZ.mp4",
  "https://i.imgur.com/xsKyTyV.mp4",
  "https://i.imgur.com/3cJ8Ezy.mp4",
  "https://i.imgur.com/A1UzkwR.mp4",
  "https://i.imgur.com/5wwG25g.mp4",
  "https://i.imgur.com/jEnKP7C.mp4",
  "https://i.imgur.com/mcSD7zj.mp4",
  "https://i.imgur.com/L8WTZOe.mp4",
  "https://i.imgur.com/hXtMffl.mp4",
  "https://i.imgur.com/bgx6dfy.mp4",
  "https://i.imgur.com/jAmSDZT.mp4",
  "https://i.imgur.com/ioHoEwZ.mp4",
  "https://i.imgur.com/2u5Fp4F.mp4",
  "https://i.imgur.com/EeFlZrB.mp4",
  "https://i.imgur.com/727GpEH.mp4",
  "https://i.imgur.com/DyR0LG1.mp4",
  "https://i.imgur.com/tMTug7j.mp4",
  "https://i.imgur.com/YidxDbU.mp4",
  "https://i.imgur.com/SQoV4df.mp4",
  "https://i.imgur.com/kgekWfF.mp4",
  "https://i.imgur.com/WTRzUS0.mp4",
  "https://i.imgur.com/05XTetT.mp4",
  "https://i.imgur.com/cDXr23S.mp4",
  "https://i.imgur.com/qjIeXci.mp4",
  "https://i.imgur.com/RGYHHRM.mp4",
  "https://i.imgur.com/SM1pZJL.mp4",
  "https://i.imgur.com/eV9IB9N.mp4",
  "https://i.imgur.com/O0Om6rI.mp4",
  "https://i.imgur.com/XTnaZaJ.mp4",
  "https://i.imgur.com/s6OFk18.mp4",
  "https://i.imgur.com/tIhc3bx.mp4",
  "https://i.imgur.com/EVt1b5m.mp4",
  "https://i.imgur.com/WErF3uV.mp4",
  "https://i.imgur.com/K9TbsGc.mp4",
  "https://i.imgur.com/Xv6CKpC.mp4",
  "https://i.imgur.com/mwKOgd8.mp4",
  "https://i.imgur.com/zb8AmwW.mp4",
  "https://i.imgur.com/5vsLdkw.mp4",
  "https://i.imgur.com/msalS8t.mp4",
  "https://i.imgur.com/4Y7gK9i.mp4",
  "https://i.imgur.com/tUDUEtc.mp4",
  "https://i.imgur.com/CEALr4l.mp4",
  "https://i.imgur.com/pwtMWYI.mp4",
  "https://i.imgur.com/5orFI43.mp4",
  "https://i.imgur.com/vqRyNCV.mp4",
  "https://i.imgur.com/zrXPSrr.mp4",
  "https://i.imgur.com/UjPz94q.mp4",
  "https://i.imgur.com/szI1tlX.mp4",
  "https://i.imgur.com/5GO8wOS.mp4",
  "https://i.imgur.com/5cl8mYW.mp4",
  "https://i.imgur.com/ERyqDST.mp4",
  "https://i.imgur.com/hhV9keY.mp4",
  "https://i.imgur.com/dhHWgTK.mp4",
  "https://i.imgur.com/LODPRSg.mp4",
  "https://i.imgur.com/A7jwSvB.mp4",
  "https://i.imgur.com/TcGQ0vq.mp4",
  "https://i.imgur.com/jwFIJed.mp4",
  "https://i.imgur.com/YusC0xr.mp4",
  "https://i.imgur.com/yPJPv4q.mp4",
  "https://i.imgur.com/kv6B97I.mp4",
  "https://i.imgur.com/ZmyPBBF.mp4",
  "https://i.imgur.com/5vsLdkw.mp4",
  "https://i.imgur.com/zrXPSrr.mp4",
  "https://i.imgur.com/5vzomnU.mp4",
  "https://i.imgur.com/UjPz94q.mp4",
  "https://i.imgur.com/yFrCWKY.mp4",
  "https://i.imgur.com/LODPRSg.mp4",
  "https://i.imgur.com/BbHnJML.mp4",
  "https://i.imgur.com/kv6B97I.mp4",
  "https://i.imgur.com/1foNZZM.mp4",
  "https://i.imgur.com/Yd3BOZr.mp4",
  "https://i.imgur.com/dmz3csF.mp4",
  "https://i.imgur.com/5vzomnU.mp4",
  "https://i.imgur.com/TcGQ0vq.mp4",
  "https://i.imgur.com/mlAPSQj.mp4",
  "https://i.imgur.com/HhD9Pw7.mp4",
  "https://i.imgur.com/ava5Utg.mp4",
  "https://i.imgur.com/knkStTE.mp4",
  "https://i.imgur.com/oZUcIih.mp4",
  "https://i.imgur.com/cRxj0AN.mp4",
  "https://i.imgur.com/jwFIJed.mp4",
  "https://i.imgur.com/RNtgDlt.mp4",
  "https://i.imgur.com/PuHerYZ.mp4",
  "https://i.imgur.com/yPJPv4q.mp4",
  "https://i.imgur.com/Qy7kmIU.mp4",
  "https://i.imgur.com/4UEWszw.mp4",
  "https://i.imgur.com/7Dvm4g7.mp4",
  "https://i.imgur.com/GoWRsbs.mp4",
  "https://i.imgur.com/zrXPSrr.mp4",
  "https://i.imgur.com/5vzomnU.mp4",
  "https://i.imgur.com/mlAPSQj.mp4",
  "https://i.imgur.com/swqikQN.mp4",
  "https://i.imgur.com/0z8ppON.mp4",
  "https://i.imgur.com/vqRyNCV.mp4",
  "https://i.imgur.com/5vsLdkw.mp4",
  "https://i.imgur.com/oZUcIih.mp4",
  "https://i.imgur.com/4UEWszw.mp4",
  "https://i.imgur.com/R9N7YCd.mp4",
  "https://i.imgur.com/Pbd7rVW.mp4",
  "https://i.imgur.com/zrXPSrr.mp4",
  "https://i.imgur.com/3UEW4Eq.mp4",
  "https://i.imgur.com/Xj0zuKJ.mp4",
  "https://i.imgur.com/a7TEDRg.mp4",
  "https://i.imgur.com/eVEoKmb.mp4",
  "https://i.imgur.com/4Y7gK9i.mp4",
  "https://i.imgur.com/H3t7YUV.mp4",
  "https://i.imgur.com/tsWOUFA.mp4",
  "https://i.imgur.com/dmz3csF.mp4",
  "https://i.imgur.com/Qy7kmIU.mp4",
  "https://i.imgur.com/swqikQN.mp4",
  "https://i.imgur.com/tjEKHN3.mp4",
  "https://i.imgur.com/3UEW4Eq.mp4",
  "https://i.imgur.com/4Y7gK9i.mp4",
  "https://i.imgur.com/8gRU2rG.mp4",
  "https://i.imgur.com/UjPz94q.mp4",
  "https://i.imgur.com/haxhpmz.mp4",
  "https://i.imgur.com/Lk2kChp.mp4",
  "https://i.imgur.com/GI4x41d.mp4",
  "https://i.imgur.com/4Y7gK9i.mp4",
  "https://i.imgur.com/yPJPv4q.mp4",
  "https://i.imgur.com/z88hoDp.mp4",
  "https://i.imgur.com/0z8ppON.mp4",
  "https://i.imgur.com/NJJkJ0e.mp4",
  "https://i.imgur.com/P9FEJuy.mp4",
  "https://i.imgur.com/rXpxjRa.mp4",
  "https://i.imgur.com/ERyqDST.mp4",
  "https://i.imgur.com/zg84Cyp.mp4",
  "https://i.imgur.com/0lKNNvA.mp4",
  "https://i.imgur.com/swqikQN.mp4",
  "https://i.imgur.com/vqRyNCV.mp4",
  "https://i.imgur.com/BbHnJML.mp4",
  "https://i.imgur.com/HMX0nKd.mp4",
  "https://i.imgur.com/WjVfowo.mp4",
  "https://i.imgur.com/knkStTE.mp4",
  "https://i.imgur.com/oZUcIih.mp4",
  "https://i.imgur.com/a7TEDRg.mp4",
  "https://i.imgur.com/ERyqDST.mp4",
  "https://i.imgur.com/k7dWZLk.mp4",
  "https://i.imgur.com/br7xCek.mp4",
  "https://i.imgur.com/5orFI43.mp4",
  "https://i.imgur.com/knkStTE.mp4",
  "https://i.imgur.com/HhD9Pw7.mp4",
  "https://i.imgur.com/z88hoDp.mp4",
  "https://i.imgur.com/dhHWgTK.mp4",
  "https://i.imgur.com/RqHUF5K.mp4",
  "https://i.imgur.com/1DLM4aU.mp4",
  "https://i.imgur.com/7Dvm4g7.mp4",
  "https://i.imgur.com/8aRAdEt.mp4",
  "https://i.imgur.com/k23iANS.mp4",
  "https://i.imgur.com/ava5Utg.mp4",
  "https://i.imgur.com/7Dvm4g7.mp4",
  "https://i.imgur.com/g2A0NbR.mp4",
  "https://i.imgur.com/ERyqDST.mp4",
  "https://i.imgur.com/dmz3csF.mp4",
  "https://i.imgur.com/BbHnJML.mp4",
  "https://i.imgur.com/GoWRsbs.mp4",
  "https://i.imgur.com/XUtldkn.mp4",
  "https://i.imgur.com/bV9UMkm.mp4",
  "https://i.imgur.com/y2mFbfq.mp4",
  "https://i.imgur.com/vqRyNCV.mp4",
  "https://i.imgur.com/7Dvm4g7.mp4",
  "https://i.imgur.com/dzuBaia.mp4",
  "https://i.imgur.com/ava5Utg.mp4",
  "https://i.imgur.com/Zwr06lD.mp4",
  "https://i.imgur.com/Qy7kmIU.mp4",
  "https://i.imgur.com/lsNhYMJ.mp4",
  "https://i.imgur.com/br7xCek.mp4",
  "https://i.imgur.com/5cl8mYW.mp4",
  "https://i.imgur.com/y2mFbfq.mp4",
  "https://i.imgur.com/LODPRSg.mp4",
  "https://i.imgur.com/Zwr06lD.mp4",
  "https://i.imgur.com/msalS8t.mp4",
  "https://i.imgur.com/GF2xE7b.mp4",
  "https://i.imgur.com/PuHerYZ.mp4",
  "https://i.imgur.com/5GO8wOS.mp4",
  "https://i.imgur.com/dzuBaia.mp4",
  "https://i.imgur.com/awxwjWw.mp4",
  "https://i.imgur.com/CCXaXpn.mp4",
  "https://i.imgur.com/W7tiRYa.mp4",
  "https://i.imgur.com/Xj0zuKJ.mp4",
  "https://i.imgur.com/H3t7YUV.mp4",
  "https://i.imgur.com/yFrCWKY.mp4",
  "https://i.imgur.com/yGRJC3P.mp4",
  "https://i.imgur.com/7Dvm4g7.mp4",
  "https://i.imgur.com/deWuoEx.mp4",
  "https://i.imgur.com/Lk2kChp.mp4",
  "https://i.imgur.com/c7g6q22.mp4",
  "https://i.imgur.com/WjVfowo.mp4",
  "https://i.imgur.com/4Y7gK9i.mp4",
  "https://i.imgur.com/knkStTE.mp4",
  "https://i.imgur.com/4MzJAbm.mp4",
  "https://i.imgur.com/BbIjHX4.mp4",
  "https://i.imgur.com/CEALr4l.mp4",
  "https://i.imgur.com/5orFI43.mp4",
  "https://i.imgur.com/GoWRsbs.mp4",
  "https://i.imgur.com/Zwr06lD.mp4",
  "https://i.imgur.com/7Dvm4g7.mp4",
  "https://i.imgur.com/k7dWZLk.mp4",
  "https://i.imgur.com/EXAf0wt.mp4",
  "https://i.imgur.com/UjPz94q.mp4",
  "https://i.imgur.com/LODPRSg.mp4",
  "https://i.imgur.com/Yd3BOZr.mp4",
  "https://i.imgur.com/T5XpsU9.mp4",
  "https://i.imgur.com/8Wrl3mS.mp4",
  "https://i.imgur.com/dzuBaia.mp4",
  "https://i.imgur.com/BbIjHX4.mp4",
  "https://i.imgur.com/bV9UMkm.mp4",
  "https://i.imgur.com/CEALr4l.mp4",
  "https://i.imgur.com/UjPz94q.mp4",
  "https://i.imgur.com/4MzJAbm.mp4",
  "https://i.imgur.com/wb46oYQ.mp4",
  "https://i.imgur.com/rXpxjRa.mp4",
  "https://i.imgur.com/Qy7kmIU.mp4",
  "https://i.imgur.com/sPi2RHJ.mp4",
  "https://i.imgur.com/rXpxjRa.mp4",
  "https://i.imgur.com/4MzJAbm.mp4",
  "https://i.imgur.com/1LDqC3Q.mp4",
  "https://i.imgur.com/v7vhGup.mp4",
  "https://i.imgur.com/GoWRsbs.mp4",
  "https://i.imgur.com/pkSzgHG.mp4",
  "https://i.imgur.com/y2mFbfq.mp4",
  "https://i.imgur.com/ava5Utg.mp4",
  "https://i.imgur.com/0z8ppON.mp4",
  "https://i.imgur.com/y2mFbfq.mp4",
  "https://i.imgur.com/BbHnJML.mp4",
  "https://i.imgur.com/CCXaXpn.mp4",
  "https://i.imgur.com/LODPRSg.mp4",
  "https://i.imgur.com/lsNhYMJ.mp4",
  "https://i.imgur.com/c7g6q22.mp4",
  "https://i.imgur.com/ERyqDST.mp4",
  "https://i.imgur.com/hihJmJC.mp4",
  "https://i.imgur.com/BbHnJML.mp4",
  "https://i.imgur.com/8fwXHg5.mp4",
  "https://i.imgur.com/pkSzgHG.mp4",
  "https://i.imgur.com/1LDqC3Q.mp4",
  "https://i.imgur.com/fu5IEDX.mp4",
  "https://i.imgur.com/WjVfowo.mp4",
  "https://i.imgur.com/cRxj0AN.mp4",
  "https://i.imgur.com/blwauOy.mp4",
  "https://i.imgur.com/WjVfowo.mp4",
  "https://i.imgur.com/Qy7kmIU.mp4",
  "https://i.imgur.com/msalS8t.mp4",
  "https://i.imgur.com/awxwjWw.mp4",
  "https://i.imgur.com/VnE3SBz.mp4",
  "https://i.imgur.com/oJQT2G9.mp4",
  "https://i.imgur.com/LODPRSg.mp4",
  "https://i.imgur.com/1foNZZM.mp4",
  "https://i.imgur.com/HQaDwg0.mp4",
  "https://i.imgur.com/R9N7YCd.mp4",
  "https://i.imgur.com/knkStTE.mp4",
  "https://i.imgur.com/BbHnJML.mp4",
  "https://i.imgur.com/IgTrpCR.mp4",
  "https://i.imgur.com/LlIji4C.mp4",
  "https://i.imgur.com/zrXPSrr.mp4",
  "https://i.imgur.com/0z8ppON.mp4",
  "https://i.imgur.com/Yd3BOZr.mp4",
  "https://i.imgur.com/GF2xE7b.mp4",
  "https://i.imgur.com/LODPRSg.mp4",
  "https://i.imgur.com/P2lGzUP.mp4",
  "https://i.imgur.com/haxhpmz.mp4",
  "https://i.imgur.com/ERyqDST.mp4",
  "https://i.imgur.com/UjPz94q.mp4",
  "https://i.imgur.com/WjVfowo.mp4",
  "https://i.imgur.com/ZmyPBBF.mp4",
  "https://i.imgur.com/hihJmJC.mp4",
  "https://i.imgur.com/8Wrl3mS.mp4",
  "https://i.imgur.com/dCXTPvv.mp4",
  "https://i.imgur.com/NJJkJ0e.mp4",
  "https://i.imgur.com/ava5Utg.mp4",
  "https://i.imgur.com/BbHnJML.mp4",
  "https://i.imgur.com/Lk2kChp.mp4",
  "https://i.imgur.com/RNtgDlt.mp4",
  "https://i.imgur.com/8fwXHg5.mp4",
  "https://i.imgur.com/dzuBaia.mp4",
  "https://i.imgur.com/v7vhGup.mp4",
  "https://i.imgur.com/dmz3csF.mp4",
  "https://i.imgur.com/pkSzgHG.mp4",
  "https://i.imgur.com/PuHerYZ.mp4",
  "https://i.imgur.com/0lKNNvA.mp4",
  "https://i.imgur.com/yFrCWKY.mp4",
  "https://i.imgur.com/GF2xE7b.mp4",
  "https://i.imgur.com/R9N7YCd.mp4",
  "https://i.imgur.com/5GO8wOS.mp4",
  "https://i.imgur.com/gpqUJkJ.mp4",
  "https://i.imgur.com/5orFI43.mp4",
  "https://i.imgur.com/z88hoDp.mp4",
  "https://i.imgur.com/1LDqC3Q.mp4",
  "https://i.imgur.com/bV9UMkm.mp4",
  "https://i.imgur.com/bV9UMkm.mp4",
  "https://i.imgur.com/lsNhYMJ.mp4",
  "https://i.imgur.com/0z8ppON.mp4",
  "https://i.imgur.com/ttaHtVa.mp4",
  "https://i.imgur.com/tUDUEtc.mp4",
  "https://i.imgur.com/1foNZZM.mp4",
  "https://i.imgur.com/tER3Lyw.mp4",
  "https://i.imgur.com/8ZvTo7C.mp4",
  "https://i.imgur.com/5BGsgYw.mp4",
  "https://i.imgur.com/dmz3csF.mp4",
  "https://i.imgur.com/hihJmJC.mp4",
  "https://i.imgur.com/szI1tlX.mp4",
  "https://i.imgur.com/swqikQN.mp4",
  "https://i.imgur.com/UjPz94q.mp4",
  "https://i.imgur.com/dzuBaia.mp4",
  "https://i.imgur.com/7Dvm4g7.mp4",
  "https://i.imgur.com/EDZ4qg5.mp4",
  "https://i.imgur.com/haxhpmz.mp4",
  "https://i.imgur.com/BbIjHX4.mp4",
  "https://i.imgur.com/eVEoKmb.mp4",
  "https://i.imgur.com/CCXaXpn.mp4",
  "https://i.imgur.com/dzuBaia.mp4",
  "https://i.imgur.com/kv6B97I.mp4",
  "https://i.imgur.com/oJQT2G9.mp4",
  "https://i.imgur.com/RqHUF5K.mp4",
  "https://i.imgur.com/BbIjHX4.mp4",
  "https://i.imgur.com/yPJPv4q.mp4",
  "https://i.imgur.com/v7vhGup.mp4",
  "https://i.imgur.com/1foNZZM.mp4",
  "https://i.imgur.com/8fwXHg5.mp4",
  "https://i.imgur.com/BbIjHX4.mp4",
  "https://i.imgur.com/LlIji4C.mp4",
  "https://i.imgur.com/H3t7YUV.mp4",
  "https://i.imgur.com/Ff0C8tf.mp4",
  "https://i.imgur.com/8ZvTo7C.mp4",
  "https://i.imgur.com/a7TEDRg.mp4",
  "https://i.imgur.com/8fwXHg5.mp4",
  "https://i.imgur.com/z88hoDp.mp4",
  "https://i.imgur.com/44AVXmi.mp4",
  "https://i.imgur.com/5orFI43.mp4",
  "https://i.imgur.com/zg84Cyp.mp4",
  "https://i.imgur.com/cRxj0AN.mp4",
  "https://i.imgur.com/zg84Cyp.mp4",
  "https://i.imgur.com/5vsLdkw.mp4",
  "https://i.imgur.com/k7dWZLk.mp4",
  "https://i.imgur.com/kv6B97I.mp4",
  "https://i.imgur.com/HQaDwg0.mp4",
  "https://i.imgur.com/BlXzK9Y.mp4",
  "https://i.imgur.com/CEALr4l.mp4",
  "https://i.imgur.com/NJJkJ0e.mp4",
  "https://i.imgur.com/pLnLojs.mp4",
  "https://i.imgur.com/LlIji4C.mp4",
  "https://i.imgur.com/LlIji4C.mp4",
  "https://i.imgur.com/ZmyPBBF.mp4",
  "https://i.imgur.com/zb8AmwW.mp4",
  "https://i.imgur.com/GoWRsbs.mp4",
  "https://i.imgur.com/bV9UMkm.mp4",
  "https://i.imgur.com/kv6B97I.mp4",
  "https://i.imgur.com/oZUcIih.mp4",
  "https://i.imgur.com/Ff0C8tf.mp4",
  "https://i.imgur.com/LlIji4C.mp4",
  "https://i.imgur.com/p1CGRgZ.mp4",
  "https://i.imgur.com/5cl8mYW.mp4",
  "https://i.imgur.com/0z8ppON.mp4",
  "https://i.imgur.com/A7jwSvB.mp4",
  "https://i.imgur.com/ERyqDST.mp4",
  "https://i.imgur.com/ZmyPBBF.mp4",
  "https://i.imgur.com/BbIjHX4.mp4",
  "https://i.imgur.com/4Y7gK9i.mp4",
  "https://i.imgur.com/LODPRSg.mp4",
  "https://i.imgur.com/T5XpsU9.mp4",
  "https://i.imgur.com/z88hoDp.mp4",
  "https://i.imgur.com/CEALr4l.mp4",
  "https://i.imgur.com/sPi2RHJ.mp4",
  "https://i.imgur.com/rwS4xzp.mp4",
  "https://i.imgur.com/3UEW4Eq.mp4",
  "https://i.imgur.com/swqikQN.mp4",
  "https://i.imgur.com/zFGivf3.mp4",
  "https://i.imgur.com/5orFI43.mp4",
  "https://i.imgur.com/zrXPSrr.mp4",
  "https://i.imgur.com/dmz3csF.mp4",
  "https://i.imgur.com/HQaDwg0.mp4",
  "https://i.imgur.com/4MzJAbm.mp4",
  "https://i.imgur.com/p1CGRgZ.mp4",
  "https://i.imgur.com/yGRJC3P.mp4",
  "https://i.imgur.com/XUtldkn.mp4",
  "https://i.imgur.com/WjVfowo.mp4",
  "https://i.imgur.com/yPJPv4q.mp4",
  "https://i.imgur.com/knkStTE.mp4",
  "https://i.imgur.com/rXpxjRa.mp4",
  "https://i.imgur.com/ERyqDST.mp4",
  "https://i.imgur.com/zb8AmwW.mp4",
  "https://i.imgur.com/7Dvm4g7.mp4",
  "https://i.imgur.com/4UEWszw.mp4",
  "https://i.imgur.com/szI1tlX.mp4",
  "https://i.imgur.com/sPi2RHJ.mp4",
  "https://i.imgur.com/dmz3csF.mp4",
  "https://i.imgur.com/CEALr4l.mp4",
  "https://i.imgur.com/LODPRSg.mp4",
  "https://i.imgur.com/zg84Cyp.mp4",
  "https://i.imgur.com/ERyqDST.mp4",
  "https://i.imgur.com/A7jwSvB.mp4",
  "https://i.imgur.com/Qy7kmIU.mp4",
  "https://i.imgur.com/5BGsgYw.mp4",
  "https://i.imgur.com/rXpxjRa.mp4",
  "https://i.imgur.com/oZUcIih.mp4",
  "https://i.imgur.com/7Dvm4g7.mp4",
  "https://i.imgur.com/swqikQN.mp4",
  "https://i.imgur.com/5vsLdkw.mp4",
  "https://i.imgur.com/awxwjWw.mp4",
  "https://i.imgur.com/bV9UMkm.mp4",
  "https://i.imgur.com/5GO8wOS.mp4",
  "https://i.imgur.com/k7dWZLk.mp4",
  "https://i.imgur.com/HhD9Pw7.mp4",
  "https://i.imgur.com/P9FEJuy.mp4",
  "https://i.imgur.com/szI1tlX.mp4",
  "https://i.imgur.com/LODPRSg.mp4",
  "https://i.imgur.com/H3t7YUV.mp4",
  "https://i.imgur.com/zb8AmwW.mp4",
  "https://i.imgur.com/4UEWszw.mp4"];
var so = [
  "1","1","1"
];
const tao = so[Math.floor(Math.random()*so.length)];
  let image = [];
 for(let i = 0; i < tao; i++) {
   const a = tpk[Math.floor(Math.random()*tpk.length)];
    const stream = (await axios.get(a, {
        responseType: "stream"
    })).data;
    image.push(stream);
};
  const msg = {
    body: ` ⏰𝗧𝗶𝗺𝗲: ${moment().tz('Asia/Ho_Chi_Minh').format('HH:mm:ss')}\n⏳𝗧𝗵𝗼̛̀𝗶 𝗴𝗶𝗮𝗻 𝗼𝗻𝗹: ${hours}:${minutes}:${seconds}\n🤖𝗣𝗿𝗲𝗳𝗶𝘅 𝗛𝗲̣̂ 𝗧𝗵𝗼̂́𝗻𝗴: ${global.config.PREFIX}\n⚙️𝗧𝗶̀𝗻𝗵 𝘁𝗿𝗮̣𝗻𝗴: ${trinhtrang}\n⏲️𝗧𝗼̂́𝗰 đ𝗼̣̂ 𝘅𝘂̛̉ 𝗹𝘆́: ${xuly} 𝗴𝗶𝗮̂𝘆\n⏳Đ𝗼̣̂ 𝘁𝗿𝗲̂̃: ${Date.now() - timeStart}ms`,
    attachment: image
};
    api.sendMessage(msg,event.threadID, (err, info) => {
    global.client.handleReaction.push({
      name: this.config.name, 
      messageID: info.messageID,
      author: event.senderID,
    })
    },event.messageID);
     }
module.exports.handleReaction = async ({ event, api, handleReaction, Currencies, Users}) => {
const axios = global.nodemodule["axios"];
const fs = global.nodemodule["fs-extra"];
const { threadID,reaction,messageID, userID } = event;
if (reaction == '👩‍❤️‍👩') {
  api.unsendMessage(handleReaction.messageID);
var msg = `📗 ==== 𝗟𝗜𝗦𝗧 𝗖𝗢𝗠𝗠𝗔𝗡𝗗 ====📗 
━━━━━━━━━━━━━━━━━━━━━
𝟭. !𝗵𝗲𝗹𝗽 𝗮𝗹𝗹 𝗵𝗼𝗮̣̆𝗰 𝘁𝗲̂𝗻 𝗹𝗲̣̂𝗻𝗵
𝟮. 𝗱𝘂̀𝗻𝗴 !𝗵𝗲𝗹𝗽: 𝗻𝗲̂́𝘂 𝗺𝘂𝗼̂́𝗻 𝘅𝗲𝗺 𝘁𝗮̂́𝘁 𝗰𝗮̉ 𝗹𝗲̣̂𝗻𝗵 𝗯𝗼𝘁 𝗰𝗼́
𝟯. 𝗱𝘂̀𝗻𝗴 !𝗰𝗵𝗲𝗰𝗸𝘁𝘁: đ𝗲̂̉ 𝘅𝗲𝗺 𝘀𝗼̂́ 𝘁𝗶𝗻 𝗻𝗵𝗮̆́𝗻 𝗺𝗮̀ 𝗯𝗮̣𝗻 đ𝗮̃ 𝗻𝗵𝗮̆́𝗻
𝟰. 𝗱𝘂̀𝗻𝗴 !𝗰𝗵𝗲𝗰𝗸: 𝗻𝗲̂́𝘂 𝗺𝘂𝗼̂́𝗻 𝘅𝗲𝗺 𝗰𝗮́𝗰 𝗹𝗲̣̂𝗻𝗵 𝘃𝗲̂̀ 𝗰𝗵𝗲𝗰𝗸
𝟱. !𝗯𝗼𝘅 𝗶𝗻𝗳𝗼: đ𝗲̂̉ 𝘅𝗲𝗺 𝘁𝗵𝗼̂𝗻𝗴 𝘁𝗶𝗻 𝘃𝗲̂̀ 𝗯𝗼𝘅 
𝟲. !𝗴𝗵𝗲𝗽: 𝗽𝗵𝗶𝗲̂𝗻 𝗯𝗮̉𝗻 𝗰𝗮𝗻𝘃𝗮𝘀 
𝟳. !𝗴𝗵𝗲́𝗽: 𝗰𝘂̃𝗻𝗴 𝗹𝗮̀ 𝗴𝗵𝗲́𝗽 𝗻𝗵𝘂̛̃𝗻𝗴 𝗹𝗮̀ 𝗽𝗵𝗶𝗲̂𝗻 𝗯𝗮̉𝗻 𝘁𝗶𝗻𝗱𝗲𝗿
𝟴. !𝗹𝗼𝗰𝗺𝗲𝗺: 𝗹𝗼̣𝗰 𝗻𝗵𝘂̛̃𝗻𝗴 𝘁𝗵𝗮̀𝗻𝗵 𝘃𝗶𝗲̂𝗻 𝗸𝗵𝗼̂𝗻𝗴 𝘁𝘂̛𝗼̛𝗻𝗴 𝘁𝗮́𝗰
𝟵. !𝘀𝗲𝘁𝗻𝗮𝗺𝗲 + 𝘁𝗲̂𝗻: 𝘀𝗲𝘁 𝗯𝗶𝗲̣̂𝘁 𝗱𝗮𝗻𝗵 𝗰𝘂̉𝗮 𝗯𝗮̣𝗻 𝗼̛̉ 𝗻𝗵𝗼́𝗺
𝟭𝟬. !𝘆𝗼𝘂𝘁𝘂𝗯𝗲 & 𝘁𝗲̂𝗻 𝗰𝗹𝗶𝗽: 𝘁𝗮̉𝗶 𝗰𝗹𝗶𝗽 𝘁𝗿𝗲̂𝗻 𝘆𝘁𝗯
𝟭𝟭. !𝘁𝗶𝗸𝘁𝗼𝗸: 𝘁𝗮̉𝗶 𝘃𝗶𝗱𝗲𝗼 𝘁𝗶𝗸𝘁𝗼𝗸 𝗱𝘂̀𝗻𝗴 𝗹𝗲̣̂𝗻𝗵 𝗱̶𝗲̂̉ 𝗯𝗶𝗲̂́𝘁 𝗰𝗵𝗶 𝘁𝗶𝗲̂́𝘁
𝟭𝟮. !𝘀𝗶𝗻𝗴 𝗼𝗿 𝘁𝗲̂𝗻 𝗯𝗮̀𝗶 𝗵𝗮́𝘁: 𝗽𝗵𝗮́𝘁 𝗯𝗮̀𝗶 𝗵𝗮́𝘁 𝗱𝗮̣𝗻𝗴 𝘃𝗼𝗶𝗰𝗲𝘀
𝟭𝟯. !𝗶𝗻𝗳𝗼: 𝘅𝗲𝗺 𝘁𝗵𝗼̂𝗻𝗴 𝘁𝗶𝗻 𝘃𝗲̂̀ 𝗮𝗰𝗰 𝗰𝘂̉𝗮 𝗯𝗮̣𝗻
𝟭𝟰. !𝗶𝗺𝗴𝘂𝗿 + 𝗿𝗲𝗽𝗹𝘆 𝗮̉𝗻𝗵: 𝗹𝗮̂́𝘆 𝗹𝗶𝗻𝗸 𝗶𝗺𝗴𝘂𝗿
𝟭𝟱. !𝗻𝗲𝘁𝗮𝗻𝗵 & 𝗿𝗲𝗽𝗹𝘆 𝗮̉𝗻𝗵: 𝗹𝗮̀𝗺 𝗻𝗲́𝘁 𝗮̉𝗻𝗵 𝗺𝗮̀ 𝗯𝗮̣𝗻 𝗿𝗲𝗽𝗹𝘆
𝟭𝟲. !𝗮𝘃𝘁𝗱𝗼𝗶: 𝗴𝘂̛̉𝗶 𝗮𝘃𝘁𝗱𝗼𝗶 𝘁𝗵𝗲𝗼 𝗯𝗮̣𝗻 𝗰𝗵𝗼̣𝗻
𝟭𝟳. 𝗾𝗿 + 𝗾𝗿𝘀: 𝗹𝗮̀𝗺 𝗾𝗿 𝘃𝗮̀ 𝗾𝘂𝗲́𝘁 𝗾𝗿

🌸 𝗣𝗵𝗶́𝗮 𝘁𝗿𝗲̂𝗻  𝗗𝘂𝗻𝗴 𝗻𝗵𝘂̛̃𝗻𝗴 𝗹𝗲̣̂𝗻𝗵 𝘁𝗵𝘂̛𝗼̛̀𝗻𝗴 đ𝘂̛𝗼̛̣𝗰 𝘀𝘂̛̉ 𝗱𝘂̣𝗻𝗴
`
        return api.sendMessage({body: msg, attachment: (await global.nodemodule["axios"]({
url: (await global.nodemodule["axios"]('https://apivip.nvt20011.repl.co/image/loli')).data.url,
method: "GET",
responseType: "stream"
})).data
},event.threadID);
}
else if (reaction == '👬') {
  api.unsendMessage(handleReaction.messageID);
    return api.sendMessage(`👑 === 𝗧𝗛𝗢̂𝗡𝗚 𝗧𝗜𝗡 𝗔𝗗𝗠𝗜𝗡 ===👑
━━━━━━━━━━━━━━━━━━━━
👤 𝗧𝗲̂𝗻: 𝗡𝗴𝘂𝘆𝗲̂̃𝗻 Tấn tiến
🔰 𝗕𝗶𝗲̣̂𝘁 𝗱𝗮𝗻𝗵:  𝗞𝗶𝘇𝘇
🦁 𝗖𝘂𝗻𝗴: 𝗕𝗮̉𝗼 𝗯𝗶̀𝗻𝗵
👶 𝗡𝗴𝗮̀𝘆 𝘀𝗶𝗻𝗵: 19/62008
🗾 𝗡𝗼̛𝗶 𝗼̛̉: tphcm
☎️ 𝗟𝗶𝗲̂𝗻 𝗵𝗲̣̂: https://www.facebook.com/profile.php?id=100050999371837 

🌸 𝗣𝗵𝗮́𝗶 𝘁𝗿𝗲̂𝗻 𝗹𝗮̀ 𝘁𝗵𝗼̂𝗻𝗴 𝘁𝗶𝗻 𝗮𝗱𝗺𝗶𝗻 𝗰𝗵𝗶́𝗻𝗵`, event.threadID, event.messageID);
    }
  else if (reaction == '🧑‍🤝‍🧑') {
    api.unsendMessage(handleReaction.messageID);
    return api.sendMessage(`❤️ =『 𝗖𝗔́𝗖𝗛 𝗗𝗨̀𝗡𝗚 𝗖𝗢̛ 𝗕𝗔̉𝗡 』=❤️

𝗛𝘂̛𝗼̛́𝗻𝗴 𝗱𝗮̂̃𝗻 𝘀𝘂̛̉ 𝗱𝘂̣𝗻𝗴 𝗰𝗼̛ 𝗯𝗮̉𝗻!

😻 𝗡𝗵𝗮̣̂𝗽 !𝗺𝗲𝗻𝘂 𝗵𝗼𝗮̣̆𝗰 !𝗵𝗲𝗹𝗽 đ𝗲̂̉ 𝘅𝗲𝗺 𝘁𝗮̂́𝘁 𝗰𝗮̉ 𝗹𝗲̣̂𝗻𝗵 𝘁𝗿𝗲̂𝗻 𝗕𝗼𝘁
🎊 𝗡𝗵𝗮̣̂𝗽 !𝗿𝘂𝗹𝗲 đ𝗲̂̉ 𝘅𝗲𝗺 𝗹𝘂𝗮̣̂𝘁 𝗻𝗵𝗼́𝗺
𝗻𝗲̂́𝘂 𝗰𝗵𝘂̛𝗮 𝗰𝗼́ 𝗵𝗮̃𝘆 𝘁𝗵𝗲̂𝗺 𝗯𝗮̆̀𝗻𝗴 𝗰𝗮́𝗰𝗵 
🍏 !𝗿𝘂𝗹𝗲 𝗮𝗱𝗱 + [𝗟𝘂𝗮̣̂𝘁 𝗡𝗵𝗼́𝗺] đ𝗲̂̉ 𝘁𝗵𝗲̂𝗺 𝗹𝘂𝗮̣̂𝘁
🌸 !𝗗𝘂̀𝗻𝗴 𝗹𝗲̣̂𝗻𝗵 !𝗰𝗮𝗹𝗹𝗮𝗱 + [𝗟𝗼̛̀𝗶 𝗡𝗵𝗮̆́𝗻] 
đ𝗲̂̉ 𝗰𝗵𝘂𝘆𝗲̂̉𝗻 𝗹𝗼̛̀𝗶 đ𝗲̂́𝗻 𝗮𝗱𝗺𝗶𝗻

𝗖𝗼́ 𝘁𝗵𝗮̆́𝗰 𝗺𝗮̆́𝗰 𝗵𝗮𝘆 𝘃𝗮̂́𝗻 đ𝗲̂̀ 𝗴𝗶̀ 𝘁𝗵𝗶̀ 𝗹𝗶𝗲̂𝗻 
☎️ 𝗵𝗲̣̂ 𝗾𝘂𝗮 𝗳𝗮𝗰𝗲𝗯𝗼𝗼𝗸:
https://www.facebook.com/profile.php?id=100050999371837 `, event.threadID, event.messageID);
  }
else if (reaction == '💵') {
  api.unsendMessage(handleReaction.messageID);
    return api.sendMessage(`🔔 =====『 𝗧𝗛𝗨𝗘̂ 𝗕𝗢𝗧 』=====🔔
━━━━━━━━━━━━━━━━━━━━━
💵 𝗖𝗮́𝗰𝗵 𝘁𝗵𝘂̛́𝗰 𝘁𝗵𝘂𝗲̂ 𝗯𝗼𝘁
🌸 𝗧𝗵𝘂𝗲̂ 𝗯𝗼𝘁 50k/1tháng
👑 𝗡𝗴𝘂̛𝗼̛̀𝗶 𝘁𝗵𝘂𝗲̂ đ𝘂̛𝗼̛̣𝗰 𝘁𝗵𝗲̂𝗺 𝗹𝗮̀𝗺 𝗮𝗱𝗺𝗶𝗻 𝗯𝗼𝘁
☎️ 𝗟𝗶𝗲̂𝗻 𝗵𝗲̣̂: https://www.facebook.com/tony.derby.773
`, event.threadID, event.messageID);
}
  else if (reaction == '🏌️') {
    api.unsendMessage(handleReaction.messageID);
    return api.sendMessage(`
🎊 Đ𝗮̂𝘆 𝗹𝗮̀ 𝗠𝗶𝗿𝗮𝗶 𝗯𝗼𝘁 𝗞𝗶𝘇𝘇😻𝗞𝗶𝗻𝗻 đ𝘂̛𝗼̛̣𝗰 𝗮𝗱𝗺𝗶𝗻 𝗹𝗮̂́𝘆 𝘁𝘂̛̀ 𝘀𝗿𝗰 𝗱 - 𝗷𝘂𝗸𝗲 𝗰𝘂̉𝗮 𝗱𝗶𝗲̣̂𝗻 𝘃𝗲̂̀ 𝘃𝗮̀ 𝗺𝗼𝗱 𝗹𝗮̣𝗶 đ𝗲̂̉ 𝘁𝗶𝗲̂́𝗽 𝘁𝘂̣𝗰 𝗽𝗵𝗮́𝘁 𝘁𝗿𝗶𝗲̂̉𝗻
𝗠𝗼̣𝗶 𝘁𝗵𝗮̆́𝗰 𝗺𝗮̆́𝗰 𝗰𝗼́ 𝘁𝗵𝗲̂̉ 𝗹𝗶𝗲̂𝗻 𝗵𝗲̣̂ 𝗮𝗱𝗺𝗶𝗻
🌐 𝗙𝗔𝗖𝗘𝗕𝗢𝗢𝗞: https://www.facebook.com/tony.derby.773
`, event.threadID, event.messageID);
  }
    };